version: "3"

services:
  frontend:
    build: frontend
    container_name: norris-frontend
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: backend
    container_name: norris-backend
    environment:
      - TZ=US/Pacific
    ports:
      - 8500:80
